#!/usr/bin/env python3

import logging
import sys

from goodwe.et import OperationMode

from source.inverter import Inverter
from source.logger import LoggerMixin
from source.tibber_api_handler import TibberAPIHandler


def print_help_and_exit() -> None:
    print("This script allows you to interact with the inverter.")
    print("")
    print("You have to supply one of the following arguments:")
    print(" --status                    Get the current state of charge and operation mode of the inverter")
    print(" --mode {GENERAL,ECO_CHARGE} Set the operation mode of the inverter")
    print(" --tibber                    Fetches the tibber rates and writes them to the database")
    print("")
    print("It uses all the variables defined in the .env file")
    sys.exit(1)


logger = LoggerMixin("Manual Script")
root_logger = logging.getLogger()
root_logger.handlers = [h for h in root_logger.handlers if type(h) is not logging.StreamHandler]  # log to file only
logger.write_newlines_to_log_file()
logger.log.info(f"Inverter is manually controlled by the user: {sys.argv}")

try:
    match sys.argv[1:]:
        case ["--status"]:
            inverter = Inverter()
            inverter.log.name += " User"
            soc = inverter.get_state_of_charge(True)
            mode = inverter.get_operation_mode(True).name
            print(f"SoC: {soc}\nmode: {mode}")
        case ["--mode", "GENERAL" | "ECO_CHARGE" as mode_name]:
            new_mode = OperationMode[mode_name]
            inverter = Inverter()
            inverter.log.name += " User"
            last_mode = inverter.get_operation_mode(log_new_mode=True).name
            inverter.set_operation_mode(new_mode)
            print(f"last mode: {last_mode}\nnew mode: {new_mode.name}")
        case ["--tibber"]:
            tibber_api_handler = TibberAPIHandler()
            api_result = tibber_api_handler._fetch_upcoming_prices_from_api()
            all_quarter_hourly_energy_rates = tibber_api_handler._extract_energy_rates_from_api_response(api_result)
            tibber_api_handler._remove_energy_rates_from_the_past(all_quarter_hourly_energy_rates)
            tibber_api_handler.write_energy_rates_to_database(all_quarter_hourly_energy_rates)
        case _:
            print_help_and_exit()
except Exception as e:
    logger.log.exception(e)
    print(f"Error: {e}", file=sys.stderr)
    sys.exit(1)
